# -*- coding: utf-8 -*-
"""[20200717] NLP-FiniteStateAcceptor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mPEjItmyx4H72BA5mY9zD_ee1NTGNlKg

# FSA 구현

* 조심!
"""

init_state = 0
final_state = 1
trap_state = 2

delta = {0:{'a':0, 'b':1},
         1:{'a':2, 'b':1}}

def FSA(string):
    state = init_state # 초기 상태
    for s in string:
        state = delta[state][s]
        if state == trap_state:
            break
    
    answer = state in final_state # boolean
    return answer

# 실행
FSA('aabbb')

"""* final state가 iterable이어야 함!"""

init_state = 0
final_state = [1] # iterable로 만들어주기 위해 리스트를 한 것이었다!
trap_state = 2

delta = {0:{'a':0, 'b':1},
         1:{'a':2, 'b':1}}

def FSA(string):
    state = init_state # 초기 상태
    for s in string:
        state = delta[state][s]
        if state == trap_state:
            break
    
    answer = state in final_state # boolean
    return answer

# 실행
FSA('aabbb')

