# -*- coding: utf-8 -*-
"""NLP-fastText.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o1CFtK3eCxFgeO7Uvq6GNN2pl67mVkNE
"""

# 모듈 불러오기
from gensim.models import FastText
from gensim.test.utils import common_texts

print(common_texts) # 연습용 9개 문장

# fastText 모델 생성 및 학습
model = FastText(size=5, window=3, min_count=1, bucket=100)
model.build_vocab(sentences=common_texts)
model.train(sentences=common_texts, total_examples=len(common_texts), epochs=10)

# 확인
print(model.wv['human']) # human에 대한 5개의 word vector
print(model.wv['klakasdfsdjf']) # OOV인데도 word vector로 만들어짐. 어떤 형태로든 숫자로 표현.

# vocabulary 확인
print(model.wv.vocab)
print(model.wv.vocab.keys())
print(model.wv.vectors_ngrams.shape)

